String? token;
const String baseApiUrl = 'https://student.valuxapps.com/api/';
const String loginEndPoint = '/login';
const String registerEndPoint = '/register';
const String homeEndPoint = '/home';
const String getCatEndPoint = '/categories';
const String favoritesEndPoint = '/favorites';
const String profileEndPoint = '/profile';
const String updateProfileEndPoint = '/update-profile';
const String searchEndPoint = 'products/search';
const String cartsEndPoint = '/carts';
